import { connect } from 'react-redux';
import AutoComplete from './auto_complete';
import { fetchStock } from "../../actions/stock_actions";

const msp = state => {
  let quotes = ["AAPL", "ABBV", "ABT", "ACN", "ADBE", "AGN", "AIG", "ALL", "AMGN", "AMZN", "AXP", "BA", "BAC", "BIIB", "BK",
    "BKNG", "BLK", "BMY", "BRK.B", "C", "CAT", "CELG", "CHTR", "CL", "CMCSA", "COF", "COP", "COST", "CSCO", "CVS", "CVX", "DD",
    "DHR", "DIS", "DOW", "DUK", "EMR", "EXC", "F", "FB", "FDX", "GD", "GE", "GILD", "GM", "GOOG", "GOOGL", "GS", "HD", "HON", "IBM",
    "INTC", "JNJ", "JPM", "KHC", "KMI", "KO", "LLY", "LMT", "LOW", "MA", "MCD", "MDLZ", "MDT", "MET", "MMM", "MO", "MRK", "MS", "MSFT",
    "NEE", "NFLX", "NKE", "NVDA", "ORCL", "OXY", "PEP", "PFE", "PG", "PM", "PYPL", "QCOM", "RTN", "SBUX", "SLB", "SO", "SPG", "T", "TGT",
    "TXN", "UNH", "UNP", "UPS", "USB", "UTX", "V", "VZ", "WBA", "WFC", "WMT", "XOM"];
  return {
    quotes: quotes, 
  }
}

const dsp = dispatch => {
  return {
    fetchStock: (symbol) => dispatch(fetchStock(symbol))
  }
}

export default connect(msp, dsp)(AutoComplete);


// SP100_STOCK_SYMBOLS = [
//   "AAPL",
//   "ABBV",
//   "ABT",
//   "ACN",
//   "ADBE",
//   "AGN",
//   "AIG",
//   "ALL",
//   "AMGN",
//   "AMZN",
//   "AXP",
//   "BA",
//   "BAC",
//   "BIIB",
//   "BK",
//   "BKNG",
//   "BLK",
//   "BMY",
//   "BRK.B",
//   "C",
//   "CAT",
//   "CELG",
//   "CHTR",
//   "CL",
//   "CMCSA",
//   "COF",
//   "COP",
//   "COST",
//   "CSCO",
//   "CVS",
//   "CVX",
//   "DD",
//   "DHR",
//   "DIS",
//   "DOW",
//   "DUK",
//   "EMR",
//   "EXC",
//   "F",
//   "FB",
//   "FDX",
//   "GD",
//   "GE",
//   "GILD",
//   "GM",
//   "GOOG",
//   "GOOGL",
//   "GS",
//   "GS",
//   "HD",
//   "HON",
//   "IBM",
//   "INTC",
//   "JNJ",
//   "JPM",
//   "KHC",
//   "KMI",
//   "KO",
//   "LLY",
//   "LMT",
//   "LOW",
//   "MA",
//   "MCD",
//   "MDLZ",
//   "MDT",
//   "MET",
//   "MMM",
//   "MO",
//   "MRK",
//   "MS",
//   "MSFT",
//   "NEE",
//   "NFLX",
//   "NKE",
//   "NVDA",
//   "ORCL",
//   "OXY",
//   "PEP",
//   "PFE",
//   "PG",
//   "PM",
//   "PYPL",
//   "QCOM",
//   "RTN",
//   "SBUX",
//   "SLB",
//   "SO",
//   "SPG",
//   "T",
//   "TGT",
//   "TXN",
//   "UNH",
//   "UNP",
//   "UPS",
//   "USB",
//   "UTX",
//   "V",
//   "V",
//   "VZ",
//   "WBA",
//   "WFC",
//   "WMT",
//   "XOM"
// ]

